# Generated by Django 3.2.6 on 2021-08-09 19:37

## file for automatically creating table (from models)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  ## automatical created field (number of this table)
                ('title', models.CharField(default='None', max_length=5, verbose_name='Name')),
                ('intro', models.CharField(max_length=250, verbose_name='Anons')),
                ('full_text', models.TextField(verbose_name='Article')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
