# Generated by Django 3.2.6 on 2021-08-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'Information', 'verbose_name_plural': 'Information'},
        ),
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(max_length=5, verbose_name='Name'),
        ),
    ]
